### ISSUE TITLE
ERROR: Error: Drop was still null after sleep!

### ISSUE THREAD

**Issue by heihachi** [TychoTheTaco/Twitch-Drops-Bot#1]
Receiving this error when watching a channel that has 72% of the drop completed

**Comment by TychoTheTaco** [comment]
Which OS and browser are you using?

**Comment by Waflis** [comment]
I have been playing around with your script and I seem to have replicated this issue.

OS: Debian 10 ( NO GUI )
Browser: /xxxx/xxxx/xxxx/node_modules/puppeteer/.local-chromium/linux-884014/chrome-linux/chrome (installs with puppeteer )
headless: true

I did some simple testing, i see that my bot joins the channel, but it never appears on channel's viewers list even though activity status on twitch says it is watching the stream.

Decided to make a PDF to see what is wrong `await page.pdf({path: '/xxxx/xxxx/xxxx/test.pdf', format: 'A4' });`

Results? 
**This video is either unavailable or not supported in this browser. (Error #4000)** 

Installed normal chrome, specified the new path and now it works just fine. 


I believe, sometimes it says "Drop was still null after sleep!" and mixes some drops and/or names around, but works great over all! Great job @TychoTheTaco Thanks for sharing! 

I hope this will help someone!

**Comment by TychoTheTaco** [comment]
Yes, it seems like the bundled chromium does not support the video format ([according to this](https://github.com/puppeteer/puppeteer#q-what-features-does-puppeteer-not-support)) so a separate Chrome installation is required. Thanks for catching that!
