### ISSUE TITLE
[Bug] Docker image does not respect timezone of host machine when using TUI

### ISSUE THREAD

**Issue by dethmourne** [TychoTheTaco/Twitch-Drops-Bot#114]
**Describe the bug**
When using the TUI in a Docker instance, the time is listed in UTC rather than the time on the host machine.

**Screenshots**
![image](https://user-images.githubusercontent.com/14261370/169906419-246548d3-3fc7-4a02-91f3-caa15ea8e421.png)

**Logs**
[log-1653339978883.txt](https://github.com/TychoTheTaco/Twitch-Drops-Bot/files/8758065/log-1653339978883.txt)

**Comment by dethmourne** [comment]
I don't think this is a -huge- deal, but it would be nice if there was a solution for this. It's possible that I'm the dummy and the fix is in Docker somehow, too, so feel free to call me out if that's the case.

**Comment by TychoTheTaco** [comment]
It seems like there isn't actually a good cross-platform way of syncing the host timezone with the docker container. @dethmourne The solution you mentioned would not work for Windows hosts. 

I think the best solution for now is to do what @ThisIsCyreX suggested.

**Comment by dethmourne** [comment]
-e TZ is the best solution for now and Docker explicitly "defaults to running in UTC" so I think that's not on you anyhow.
