### ISSUE TITLE
[Feature Request] Sync Drop Status Progress with Drop Progress seen in  logs

### ISSUE THREAD

**Issue by dodgex** [TychoTheTaco/Twitch-Drops-Bot#116]
The Progress in the Drops Status Table is only updated like every 15 Minutes with the "Pending Drop Campaigns" Table.

It would be nice, if possible, to have the Progress time update when a new progress event is received. In the Screenshot the Progress is shown as 133 Minutes but it is already at 146 according to the logs. (at 148 the progress updated together with the pending campaigns)

![image](https://user-images.githubusercontent.com/204013/170826859-636d36b7-7efc-472e-a10b-c08072807481.png)

**Comment by TychoTheTaco** [comment]
Fixed in the latest release.
