### ISSUE TITLE
[Minor Bug] Stream Status shows Channel Points for diffrent channel

### ISSUE THREAD

**Issue by dodgex** [TychoTheTaco/Twitch-Drops-Bot#117]
As the title says, this is only a minor bug (at least to me). But i found that the Stream Status Channel Points can show the points of antoher stream running for the account. This happened while using this tool to get drops from a game while watching another channel.

The Channel Points shown every now and then, are the points of the actively watched channel instead of the one "watched" by the tool.

I think it happens because in [stream_status_table.tsx](https://github.com/TychoTheTaco/Twitch-Drops-Bot/blob/dev/src/ui/stream_status_table.tsx#L46) the `community_points_earned` event is handled to update the points. if the event payload contains the channel for which the event happens, it might make sense to check if the event is for the bot channel and ignore any other channel?

**Comment by TychoTheTaco** [comment]
Fixed in the latest release.

**Comment by dodgex** [comment]
Awesome. Thank you for your quick fixes! :)
