### ISSUE TITLE
[Minor Bug] Update Info shows current instead of new Version

### ISSUE THREAD

**Issue by dodgex** [TychoTheTaco/Twitch-Drops-Bot#122]
**Describe the bug**
Bot showed that there is an Update, but from my understanding it showed the current version but i expect it should show the new version?

**Screenshots**
The Update Info
![image](https://user-images.githubusercontent.com/204013/172782751-471eb481-27d9-45f3-8661-a93a0360e8c5.png)

After upgrade
![image](https://user-images.githubusercontent.com/204013/172782801-36e3212a-3221-4fb5-aa94-d7d785e7b000.png)

I think in first screenshot it should have shown the 1.2.1 in green?

**Comment by TychoTheTaco** [comment]
Fixed in the latest release.
