### ISSUE TITLE
[Feature Request] estimate time in progressbar

### ISSUE THREAD

**Issue by Smallinger** [TychoTheTaco/Twitch-Drops-Bot#13]
Would be cool if you could see exactly what time the drop is finished.
like the script start at 12:42 a drop that needs 30 min's so the estimate time is 13:12

**Comment by TychoTheTaco** [comment]
Seems a bit redundant because it already shows the minutes complete out of the total required, but I'll consider adding it at some point in the future.

**Comment by TychoTheTaco** [comment]
Well, it's been a while but this feature is finally here in the new (experimental) TUI mode.
