### ISSUE TITLE
Use Auth-Token instead of Login data

### ISSUE THREAD

**Issue by crazydisi** [TychoTheTaco/Twitch-Drops-Bot#130]
Hey,

i would love to see an option to put in an auth token instead of username and password?
As far as i could see it would be sufficient to set a cookie "auth-token" in the browser instance which has the value of the original auth token of a loggedin session.

**Comment by TychoTheTaco** [comment]
Added in the latest release.

**Comment by chemputer** [comment]
Could you update the Readme with how to use the auth token?

**Comment by TychoTheTaco** [comment]
@chemputer You can use it by adding `"auth_token": "myAuthToken"` to your config. I will add it to the readme also.
