### ISSUE TITLE
ETIMEDOUT error  [Bug]

### ISSUE THREAD

**Issue by ikoyhn** [TychoTheTaco/Twitch-Drops-Bot#140]
**Describe the bug**
The bot runs fine but I get this error in the logs fairly often that is saying Error: connect ETIMEDOUT and then a random IP in Sweden? Looks like it happens about once every 10min.

**Logs**
`[2022-07-01 15:35:23] [error] connect ETIMEDOUT 146.75.82.167:443 Error: connect ETIMEDOUT 146.75.82.167:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)`

**Comment by TychoTheTaco** [comment]
This is a network connection issue between your PC and Twitch, there is nothing I can do about this. If it is happening suddenly, it's possible that Twitch is having connection issues.
