### ISSUE TITLE
Question: How watching works?

### ISSUE THREAD

**Issue by maxcamorra** [TychoTheTaco/Twitch-Drops-Bot#146]
Will the bot watch the streamers i add into the config only when they are going live or will it always stay there inside the chat? And also will it watch all streamers at the same time or one by one?

**Comment by TychoTheTaco** [comment]
The bot will go through the list of streamers one by one, and if it finds one that is live, it will watch it until they go offline, then it will repeat the process to find another streamer that is live. It will only watch 1 stream at a time.
