### ISSUE TITLE
[Feature Request] broadcaster prio list even if drops are available

### ISSUE THREAD

**Issue by Pr0mises** [TychoTheTaco/Twitch-Drops-Bot#172]
As of [Twitch Rivals 2](https://twitch.facepunch.com/) it would be awesome to clarify the channels with a priority.
Every channel can enable drops for this game, but only a few channels have their own drops.
I tried to do a proper prio list to watch the streams, but it is ignored while the game itself has drops, therefore some random streams without their own drops are chosen.

E.g. the twitchrivals channel isn't always online, so I want to have it at prio1 and if the channel is online I want to claim those, before the others.
I hope that makes sense.

**Comment by TychoTheTaco** [comment]
Added in the latest release.
