### ISSUE TITLE
[Bug] Error ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by Addos223** [TychoTheTaco/Twitch-Drops-Bot#173]
Hi, what is the problem ? I'm sure that username and password are correct.
![image](https://user-images.githubusercontent.com/111061320/184132687-8ad9eeb5-0a4e-40a6-b67d-d6b8b320f2fc.png)
And that's my config,json 
![image](https://user-images.githubusercontent.com/111061320/184133049-3788be60-c0c9-4543-b342-4075f6daae3c.png)

**Comment by TychoTheTaco** [comment]
This is an issue with your network connection

**Comment by Addos223** [comment]
Alright, I figured it out. I had no internet in Docker and had to reinstall it completely. Thanks for help :)
