### ISSUE TITLE
[Bug] Uncaught exception: TypeError: campaign.allow.channels is not iterable

### ISSUE THREAD

**Issue by Jniklas2** [TychoTheTaco/Twitch-Drops-Bot#174]
**Describe the bug**
The current docker container won't work because of the error in the log file. It runs on a Debian 11 Server with the docker version 20.10.17.

**Logs**
Log file is attached.
[log-1660226675931.txt](https://github.com/TychoTheTaco/Twitch-Drops-Bot/files/9309547/log-1660226675931.txt)

**Comment by TychoTheTaco** [comment]
Fixed.
