### ISSUE TITLE
[Feature Request] Ability to watch all games after list has been completed.

### ISSUE THREAD

**Issue by ssamuel89** [TychoTheTaco/Twitch-Drops-Bot#175]
If we have a priority list such as: 

"games": ["Rocket league", "514152", "138585"], 

Having the ability to do all games once the list has been exhausted would be perfect. Something like: 

"games": ["Rocket league", "514152", "138585", "all"], 

One solution to this would be to run two containers, one with a list of game IDs and one without, but this would remove the prioritisation from the equation.

**Comment by TychoTheTaco** [comment]
You can do this already by setting `watch_unlisted_games` option to `true`. It will still prefer the games in your list, but if they are all done then it will move on to anything else.

**Comment by ssamuel89** [comment]
Perfect, thank you. Guess I should have RTFM. Haha.
