### ISSUE TITLE
Need a coooke file that created after login or structure  for manual creating.

### ISSUE THREAD

**Issue by AndyShade** [TychoTheTaco/Twitch-Drops-Bot#213]

**Comment by TychoTheTaco** [comment]
You can use an extension like [EditThisCookie](https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg?hl=en)

Just login to twitch and export the cookies to clipboard, then paste in a file called `cookies-username.json`

**Comment by AndyShade** [comment]
Ty for advice.

**Comment by TychoTheTaco** [comment]
> Ty for advice. Also i have 2 ideas to resolve login ussie with devtools-drive browsers can' login. 1.Use dev-tools and running not in private mode - how i can recognize using private mode has primary part of that problem. In normal mode login is successful 2.Some third party twich chat sofware like [chatterino](https://github.com/Chatterino/chatterino2) or [orion](https://github.com/alamminsalo/orion) (now discomtinuied but good login solution in my view) or [tc](https://github.com/mccxiv/tc) uses web page to login extract required data. A similar method could be solution to this part of the problem.
> 
> I hope my perseverance not bother you much.

Yea I will look into using the dev tools directly without puppeteer as that is more likely to work.
