### ISSUE TITLE
[Feature Request] Points collect webhook event

### ISSUE THREAD

**Issue by mincheri** [TychoTheTaco/Twitch-Drops-Bot#228]
There should be a webhook event that sends when the bot claims points alongside the type and amount.

Here is the list of possible ones:

Earning Action | Description | Points Earned
-- | -- | --
Watching | Non-subscribed viewers receive points each 5 mins of live watch time. | +10
Active watching | Non-subscriber viewers receive points each 15 mins of live watch time   (Click to redeem) | +50
Participating in a Raid | Viewers receive points for joining a raid. | +250
Watch Streak 2 | Viewers receive points for returning for 2 consecutive streams Each   stream must be at least 10 minutes long and it must have been at least 30   minutes since the last stream ended | +300
Watch Streak 3 | Viewers receive points for returning for 3 consecutive streams Each   stream must be at least 10 minutes long and it must have been at least 30   minutes since the last stream ended | +350
Watch Streak 4 | Viewers receive points for returning for 4 consecutive streams. Each   stream must be at least 10 minutes long and it must have been at least 30   minutes since the last stream ended | +400
Watch Streak 5+ | Viewers receive points for returning for 5 consecutive streams Each   stream must be at least 10 minutes long and it must have been at least 30   minutes since the last stream ended | +450

**Comment by PockySweet** [comment]
This would be amazing

**Comment by TychoTheTaco** [comment]
Added in the latest release.
