### ISSUE TITLE
[Bug] Unable to login with both login/password and auth token

### ISSUE THREAD

**Issue by bykidi** [TychoTheTaco/Twitch-Drops-Bot#238]
Logging in using login password times out with an error.
Logging in using auth token drops with Missing device ID error
twitch blocked something?

**Comment by OffensiveExile** [comment]
I appeared to have this issue to but a fix I've found is to use a cookies json file in the same location as your config file and the bot will automatically use that as long as the matching username is in the config entry.

`cookies-USERNAME.json` - replace USERNAME with your twitch username.

I personally used the EditThisCookie extension on Chrome to export the entirety of my Twitch Cookies and saved it in the file mentioned above.

**Comment by bykidi** [comment]
@OffensiveExile worked like a charm! thank you!
