### ISSUE TITLE
[Feature Request]  Possibility switch on/off autoclaim drops and bonus channel points.

### ISSUE THREAD

**Issue by AndyShade** [TychoTheTaco/Twitch-Drops-Bot#239]
That be avoid to generate GQL errors and do bot bot more stealth for twith and prevent possible crushes. Set off  by default.

**Comment by JourneyOver** [comment]
This has been added, so this issue can probably be closed now.

**Comment by AndyShade** [comment]
TY

**Comment by SyineaGaming** [comment]
> This has been added, so this issue can probably be closed now.

can you explain it?
