### ISSUE TITLE
Allowing user to select one broadcaster to watch [Feature Request] 

### ISSUE THREAD

**Issue by LunasWH** [TychoTheTaco/Twitch-Drops-Bot#259]
It would be good, if we could choose to watch broadcast of a single streamer, in order to rack up channel points and claim drops.

**Comment by TychoTheTaco** [comment]
You should be able to do this by setting `games` list to empty, setting the `broadcasters` list to 1 person that you want to watch and setting `watch_unlisted_games` to `false`
