### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by BulldozerPete** [TychoTheTaco/Twitch-Drops-Bot#289]
The current docker container isn't working: #287 
Last commit was on 3rd of Dec 2022. 

Are there any working alternatives/ forks?

**Comment by whyphyrl** [comment]
i switched to this projekt https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/ sad thing is this is "streamer based" and not "drop based"

**Comment by Chase-V** [comment]
Try this. But you need to build it, release from october is not working well

https://github.com/DevilXD/TwitchDropsMiner

**Comment by TychoTheTaco** [comment]
#287 is fixed now with #292
