### ISSUE TITLE
Docker ARM-version

### ISSUE THREAD

**Issue by Valentin-Metz** [TychoTheTaco/Twitch-Drops-Bot#30]
Many servers and the RaspberryPi run on an ARM-CPU. It'd be nice if you could build a respective docker image. (linux/arm64/v8)

**Comment by Valentin-Metz** [comment]
I have composed a working docker file.  If you tell me how you'd like it submitted, I'll open a pull request.

**Comment by BulldozerPete** [comment]
Could you also provide a how-to-guide?

thank you

**Comment by Valentin-Metz** [comment]
I have moved this into a pull request. You may find the appropriate Dockerfile there.

**Comment by BulldozerPete** [comment]
Ok, but I have no idea how to run docker.
