### ISSUE TITLE
Create how to run docker container

### ISSUE THREAD

**Issue by BulldozerPete** [TychoTheTaco/Twitch-Drops-Bot#32]
Hello,

I don’t have any idea how to run a docker container for this app.
Can someone please create a noob friendly setup guide?

thx

**Comment by BulldozerPete** [comment]
Maybe @Valentin-Metz can assist.

**Comment by Valentin-Metz** [comment]
1: Install Docker on the RaspberryPi (plenty of tutorials out there for that)
2: Clone the Repo. Enter it.
3: Build the Dockerfile (If the container is provided directly you can skip this step. Currently it is not) `sudo docker build -t twitch_drops_bot -f Dockerfile_arm32v7 .`
4: Run the container. Supply the directory of your config.json. `sudo docker run -v /home/pi/folder_with_config:/app/data -i --sig-proxy=false twitch_drop_bots`

**Comment by BulldozerPete** [comment]
Thx.

How about I write down the simple steps?
1. login to your raspberry pi via ssh
2. run `sudo apt-get update && sudo apt-get upgrade`
3. run `curl -sSL https://get.docker.com | sh`
4. run `sudo usermod -aG docker pi` from https://pimylifeup.com/raspberry-pi-docker/
5. run `logout`

now I am running into issues:
6. How do I copy the Repo?

**Comment by Valentin-Metz** [comment]
That's too detailed. We should expect people to be able to use git. If you aren't familiar with any of these steps you can always google them, as they are not repo specific.

**Comment by BulldozerPete** [comment]
Okay, then this is just for me.

But how do I copy the Repo? (your step 2)

**Comment by BulldozerPete** [comment]
6. run `git clone https://github.com/TychoTheTaco/Twitch-Drops-Bot/`
7. run `cd Twitch-Drops-Bot/`
8. run `udo docker build -t twitch_drops_bot -f Dockerfile_arm32v7 .`

Would that work?

**Comment by BulldozerPete** [comment]
I got that info after command "8":
`sudo docker build -t twitch_drops_bot -f Dockerfile_arm32v7
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile`

**Comment by BulldozerPete** [comment]
My folder is `/home/pi/Twitch-Drops-Bot`

**Comment by Valentin-Metz** [comment]
> I got that info after command "8":
> `sudo docker build -t twitch_drops_bot -f Dockerfile_arm32v7
> "docker build" requires exactly 1 argument.
> See 'docker build --help'.
> Usage:  docker build [OPTIONS] PATH | URL | -
> Build an image from a Dockerfile`

Check the command I posted. You are missing a dot at the end. It expects a directory as argument. You'll also need to clone my fork of the repo, as the respective Docker file is not merged yet.

**Comment by BulldozerPete** [comment]
I am not an expert.

**Comment by BulldozerPete** [comment]
`sudo docker build -t twitch_drops_bot -f Dockerfile_arm32v7 .`

Result:
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/pi/Twitch-Drops-Bot/Dockerfile_arm32v7: no such file or directory

**Comment by Valentin-Metz** [comment]
Delete folder and git clone this one instead (don't forget to backup your config file): https://github.com/Valentin-Metz/Twitch-Drops-Bot

**Comment by BulldozerPete** [comment]
Will do.
Haven't configured the config file yet.

**Comment by BulldozerPete** [comment]
Wow, nice automated installation. I guess that is the “magic” of docker.

I am running a 64Bit version of raspian bullseye, that shouldn't be an issue with a 32bit docker container, right?

**Comment by Valentin-Metz** [comment]
If you run 64bit, you can try to build and run the ARM64v8 instead. It might work, but no guarantees (if it doesn't, just run the v7). The RaspberryPi behaves a bit different than most systems.

**Comment by BulldozerPete** [comment]
I am still not able to start the docker container or edit the config file.

**Comment by BulldozerPete** [comment]
My folder is 
/home/pi/Twitch-Drops-Bot

**Comment by Valentin-Metz** [comment]
I'm gonna need the command you start your container with and its output/error.

**Comment by BulldozerPete** [comment]
`sudo docker run -v /home/pi/Twitch-Drops-Bot:/app/data -i --sig-proxy=false twitch_drop_bots`

result:
Unable to find image 'twitch_drop_bots:latest' locally
docker: Error response from daemon: pull access denied for twitch_drop_bots, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

**Comment by Valentin-Metz** [comment]
Give me a `docker images`.
The image you built should be in there.

**Comment by BulldozerPete** [comment]
REPOSITORY         TAG                IMAGE ID       CREATED       SIZE
twitch_drops_bot   latest             2deeeea68200   2 hours ago   1.74GB
<none>             <none>             d5a2aa12efe3   2 hours ago   1.46GB
arm64v8/node       current-bullseye   0b0dff9f0b27   8 days ago    943MB
arm32v7/node       current-bullseye   9d37242881d6   8 days ago    791MB

**Comment by Valentin-Metz** [comment]
Check the name. You named it "twitch_drops_bot" and are trying to run "twitch_drop_bot".

**Comment by BulldozerPete** [comment]
You are right.
Next try:
```
sudo docker run -v /home/pi/Twitch-Drops-Bot:/app/data -i --sig-proxy=false twitch_drops_bots
Unable to find image 'twitch_drops_bots:latest' locally
docker: Error response from daemon: pull access denied for twitch_drops_bots, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

**Comment by Valentin-Metz** [comment]
still a typo...

**Comment by BulldozerPete** [comment]
sudo docker run -v /home/pi/Twitch-Drops-Bot:/app/data -i --sig-proxy=false twitch_drops_bot
[2021-12-29 22:37:32] [info] Loading config file: config.json
[2021-12-29 22:37:32] [warn] Config file not found! Creating a default one...
[2021-12-29 22:37:32] [info] Config saved to config.json
[2021-12-29 22:37:33] [info] Logging in...
You must provide a username and password to use headless login!

**Comment by Valentin-Metz** [comment]
Well there you go. It works. Now provide a valid config file. The options are listed in the main repo.

**Comment by BulldozerPete** [comment]
Where do I create the config file?

**Comment by BulldozerPete** [comment]
Found it. It is in my /home/pi/Twitch-Drops-Bot folder.

**Comment by BulldozerPete** [comment]
I have now edited the config file.
Added a game, username and password.

Result:
```
sudo docker run -v /home/pi/Twitch-Drops-Bot:/app/data -i --sig-proxy=false twitch_drops_bot
[2021-12-29 22:45:31] [info] Loading config file: config.json
[2021-12-29 22:45:31] [error] Failed to read config file!
[2021-12-29 22:45:31] [error] Unexpected token C in JSON at position 88 SyntaxError: Unexpected token C in JSON at position 88
    at JSON.parse (<anonymous>)
    at ConfigurationParser.parse (/app/dist/configuration_parser.js:48:31)
    at Object.<anonymous> (/app/dist/index.js:82:34)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by BulldozerPete** [comment]
I fixed the error at position 88.

Result:
```
sudo docker run -v /home/pi/Twitch-Drops-Bot:/app/data -i --sig-proxy=false twitch_drops_bot
[2021-12-29 22:49:06] [info] Loading config file: config.json
[2021-12-29 22:49:07] [info] Logging in...
[2021-12-29 22:49:11] [info] Checking for email verification...
[2021-12-29 22:49:12] [info] Email verification found.
prompt: code:  123456
[2021-12-29 22:49:58] [info] Logged in as NICKNAME
[2021-12-29 22:49:58] [info] Saved cookies to ./cookies-NICKNAME.json
[2021-12-29 22:49:58] [info] Updating drop campaigns...
[2021-12-29 22:49:59] [info] Found 85 campaigns.
[2021-12-29 22:49:59] [info] Found 0 pending campaigns.
```

**Comment by Valentin-Metz** [comment]
Well, the docker image works as expected. All further errors are not with the docker image but with your config file.

**Comment by BulldozerPete** [comment]
I changed the game ID in config.json to another game, but the amount of campaigns are still the same.

```
[2021-12-29 22:53:46] [info] Updating drop campaigns...
[2021-12-29 22:53:47] [info] Found 85 campaigns.
[2021-12-29 22:53:47] [info] Found 0 pending campaigns.
```
For my favorite game, you will receive items if you watch a specific channel. Haven't read anything how to direct to one "streamer".

Am I missing someting?

**Comment by BulldozerPete** [comment]
I needed to unlink twitch to my game account and connect it again, now it works.

**Comment by BulldozerPete** [comment]
And how do I resume the docker log after logging in?

**Comment by Valentin-Metz** [comment]
You should look up some basic tutorials about the Linux, Git, Tmux and Docker.

**Comment by UrekD** [comment]
> How do I "minimize" docker in my terminal window?

Add `-d` when you do docker run ex. `docker run -d -v /home/.....`

**Comment by UrekD** [comment]
> I changed the game ID in config.json to another game, but the amount of campaigns are still the same.
> 
> ```
> [2021-12-29 22:53:46] [info] Updating drop campaigns...
> [2021-12-29 22:53:47] [info] Found 85 campaigns.
> [2021-12-29 22:53:47] [info] Found 0 pending campaigns.
> ```
> 
> For my favorite game, you will receive items if you watch a specific channel. Haven't read anything how to direct to one "streamer".
> 
> Am I missing someting?

Did you format it correctly with the "" ex. "games": [488552"], I got the same results when I forgot em.

**Comment by BulldozerPete** [comment]
I fixed the last issue already. Forgot the quotation marks.

**Comment by BulldozerPete** [comment]
I do start the container with 
sudo docker run -v /home/pi/Twitch-Drops-Bot:/app/data -i --sig-proxy=false twitch_drops_bot

Then all progress will be shown in terminal.
I do end that with crtl-c and exit terminal.
The container should be still running, right?
How do I enter the live-log again?

**Comment by BulldozerPete** [comment]
I do receive an error:

```
[2021-12-30 16:18:38] [info] Found 1 active streams
[2021-12-30 16:18:38] [info] Found 1 potential streams
[2021-12-30 16:18:38] [info] Watching stream: https://www.twitch.tv/STREAM
[2021-12-30 16:18:38] [info] Updating drop progress...
[2021-12-30 16:19:08] [error] Navigation timeout of 30000 ms exceeded TimeoutError: Navigation timeout of 30000 ms exceeded
    at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
[2021-12-30 16:19:21] [info] Found 1 active streams
```

**Comment by BulldozerPete** [comment]
Next error:

```
[2021-12-30 16:34:36] [info] Watching stream: https://www.twitch.tv/STREAM
[2021-12-30 16:34:36] [info] Updating drop progress...
[2021-12-30 16:35:09] [error] Navigation timeout of 30000 ms exceeded TimeoutError: Navigation timeout of 30000 ms exceeded
    at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
[2021-12-30 16:35:26] [error] Stream failed too many times. Giving up for 30 minutes...
```

**Comment by BulldozerPete** [comment]
I had to delete my old container because it gave me some odd error.
Now I am running into a new one.

What I did:
1. `rm -rf Twitch-Drops-Bot`
2. `git clone https://github.com/Valentin-Metz/Twitch-Drops-Bot`
3. `cd Twitch-Drops-Bot`
4. `sudo docker build -t twitch_drops_bot -f Dockerfile_arm64v8 .`

error:
```
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/debian-security/dists/bullseye-security/InRelease  Temporary failure resolving 'security.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package chromium
The command '/bin/sh -c apt-get update     && apt-get install chromium --yes' returned a non-zero code: 100
```

**Comment by Valentin-Metz** [comment]
That seems to some kind of issue with you fetching the package list. I've created a docker pagage. You can skip the build part and simply supply this as container name in the docker run command: `valentinmetz/twitch-drops-bot`

**Comment by BulldozerPete** [comment]
Okay, thank you very much!

So the steps are:
```
1. rm -rf Twitch-Drops-Bot
2. git clone https://github.com/Valentin-Metz/Twitch-Drops-Bot
3. cd Twitch-Drops-Bot
4.  sudo docker run -v valentinmetz/twitch-drops-bot -i --sig-proxy=false twitch_drops_bots
```?

**Comment by Valentin-Metz** [comment]
Check the documentation for the docker run command: https://docs.docker.com/engine/reference/commandline/run/
You only need the last command.
The `-v` links a directory in your computer into the container. It takes the location of the folder with your config.json (or creates it at the supplied location) and always needs to point into /app/data inside the container.
The command you run should look like this:
`sudo docker run -it -v /home/ubuntu/my_config_location:/app/data --sig-proxy=false valentinmetz/twitch-drops-bot`

**Comment by BulldozerPete** [comment]
Done that.

```
sudo docker run -it -v /home/pi/Twitch-Drops-Bot:/app/data --sig-proxy=false valentinmetz/twitch-drops-bot
[2021-12-30 20:33:43] [info] Loading config file: config.json
[2021-12-30 20:33:44] [info] Logging in...
[2021-12-30 20:33:44] [error] net::ERR_NAME_NOT_RESOLVED at https://www.twitch.tv/login Error: net::ERR_NAME_NOT_RESOLVED at https://www.twitch.tv/login
    at navigate (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:116:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FrameManager.navigateFrame (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:91:21)
    at async Frame.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:417:16)
    at async Page.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1156:16)
```

But I have configured the config.json properly. Just added a game ID, twitch nickname and password like:
`"games":["12345"],"username":"NICKNAME","password":"pw"`

**Comment by Valentin-Metz** [comment]
It seems like your container has trouble connecting to the internet. Your build process earlier had the same error. This is an issue with your docker, not the container.

**Comment by BulldozerPete** [comment]
Okay. Maybe something with the OS is not working.

**Comment by TychoTheTaco** [comment]
Closing this since it seems like you got everything working.
