### ISSUE TITLE
Bot watches stream for drop that is impossible to get

### ISSUE THREAD

**Issue by Valentin-Metz** [TychoTheTaco/Twitch-Drops-Bot#40]
`[2022-01-20 17:49:18] [info] Found 45 pending campaigns.
Watching https://www.twitch.tv/forhonorgame | Viewers: 9891 | Uptime: 1:00:00
WD Reveal Jan SC2 ██████████░░░░░░░░░░ 31 / 60 minutes`

The campaign ends at 18:15

**Comment by TychoTheTaco** [comment]
There's always a chance that the stream lasts a little longer than expected, or the campaign gets extended :)

But I guess I can add an option to not watch drops if it's not likely to be finished before the campaign ends.
