### ISSUE TITLE
Source code and script does not define what a "higher priority" stream is

### ISSUE THREAD

**Issue by Tecfan** [TychoTheTaco/Twitch-Drops-Bot#43]
Just saw that the software switched to a "higher priority stream". Tried to figure out why it was higher priority than other streams without success, even looked at the source code but the comment was generic.

What is a "higher priority" stream? Campaigns that are ending soon?

Edit: Disclaimer: This might be defined somewhere, but since I could not find info about it, it needs to be more dummy proofed imo. Also: I am using default configs.

**Comment by TychoTheTaco** [comment]
The list of game IDs that you have in the config is in order of priority. 

For example:
Lets assume your config has `"games": ["1", "2", "3"]`, and the bot was currently watching a stream for game `2`. The bot periodically checks if there are active campaigns/streams for the other games listed, and finds one for game `1`. Game `1` is listed first in the config, so it has a higher priority and the bot will switch to it.

If there are multiple active campaigns for a game, then it will give priority to the one that ends first. You can see how they are sorted in the code [here](https://github.com/TychoTheTaco/Twitch-Drops-Bot/blob/419f6fe9acb5e96957a7285e77034a9134cb7e8b/src/twitch_drops_bot.ts#L165).

**Comment by Tecfan** [comment]
Can this be clarified somehow for end users like me? Or explained in README.md?

**Comment by TychoTheTaco** [comment]
yes, I've just added this explanation to the readme under the `--games` option
