### ISSUE TITLE
Game Priority not working?

### ISSUE THREAD

**Issue by BuckyTM** [TychoTheTaco/Twitch-Drops-Bot#44]
I've tried to set Rainbow Six Siege and Rocket League's game ID in the config. Rainbow Six Siege at the highest priority while Rocket League is at the second. However the bot would always go for Rocket League's stream instead of Sieges' 

![Screenshot_20220131-021812427 (1)](https://user-images.githubusercontent.com/76104163/151712168-2e38915d-9f69-4719-b67a-1ff808682c1f.jpg)
![Screenshot_20220131-021659429 (1)](https://user-images.githubusercontent.com/76104163/151712172-d203c7bd-406f-4f19-a319-69225643d320.jpg)
![Screenshot_20220131-022155856 (1)](https://user-images.githubusercontent.com/76104163/151712204-b82f993b-b9b6-4523-bcdf-470d7f72790f.jpg)

**Comment by BuckyTM** [comment]
Adding them one at a time and restart seems fine

**Comment by TychoTheTaco** [comment]
The bot chose the Rocket League stream because the Rainbow Six stream did not have drops enabled (notice in the sceenshot there's no "Drops Enabled" tag for R6, but Rocket League does.
