### ISSUE TITLE
The bot will stop watching halfway through

### ISSUE THREAD

**Issue by lfz-5** [TychoTheTaco/Twitch-Drops-Bot#48]
I really appreciate your project allowing me to watch live streams and earn rewards even when my computer is off. 
The environment is: VPS with 1 core \1G Memory \Ubuntu 18.04 \Docker. 
Here are some logs.
<img width="733" alt="image" src="https://user-images.githubusercontent.com/43802521/153118210-345f12ca-0faa-4e70-bb55-165335926755.png">
In the first picture, at this [2022-02-08 11:12:04] time, the bot was cracked because of "run out of memory', so I rebooted the VPS.  After that it worked nice, helped claim a drop.
![image](https://user-images.githubusercontent.com/43802521/153118539-0e8a21e4-c17c-4dfb-9702-8417ee7a05a9.png)
But after [2022-02-08 14:25:39], the bot didn't claim any community points as you can see. And the ranibow6's stream is about 13 hours, the uptime stop at 6:25:17. And it just stop here,no more infomation. At [2022-02-09 03:10:55],  I use "docker restart". 
I checked twitch.tv/rainbow6 on my own PC, when i opened it, it started playing yesterday's video from the 6:22:41 position.
![image](https://user-images.githubusercontent.com/43802521/153119400-5ecb6d06-6f6c-46b2-bdcd-f8e7b28908e0.png)
I think this is a interesting problem, and I'm glad to help you solve it.

**Comment by lfz-5** [comment]
More information, at [2022-02-0 09:43:32], there is a error log.
<img width="461" alt="image" src="https://user-images.githubusercontent.com/43802521/153179490-4a41e792-b211-426c-892a-2b089600cb5f.png">
At that time, I use "docker restart" firstly, but the log stop here again. Then I use "docker stop" and "docker start", it worked again.

**Comment by TychoTheTaco** [comment]
Can you post the contents of the log file from around that time, it might have some extra information to see what's going on.

**Comment by lfz-5** [comment]
Thank you. I use another VPS with 2 core and 2G memory, it worked nice, I think this is the problem. And you can add some tips in the README file.
