### ISSUE TITLE
[Bug] can't log in

### ISSUE THREAD

**Issue by BulldozerPete** [TychoTheTaco/Twitch-Drops-Bot#49]
I am getting this error message:
`[error] Failed to login. There was probably an extra verification step that this app didn't check for. A screenshot of the page will be saved to failed-login-screenshot-1644515619539.png and the page content will be saved to failed-login-html-1644515619539.html. Please create an issue on GitHub with both of these files.`

But there is nothing unusual on that screenshot. Just twitch mainpage.

**Comment by TychoTheTaco** [comment]
If the screenshot looks normal, the page probably just didn't completely finish loading on time. If it keeps happening, you can try to increase `load_timeout_secs`.

**Comment by BulldozerPete** [comment]
Thx. 
I will close this issue and will create a new one if the error occurs again
