### ISSUE TITLE
Accept or throw Error when integer is used in config.json games-array

### ISSUE THREAD

**Issue by felithium** [TychoTheTaco/Twitch-Drops-Bot#54]
I just tried the bot to get drops for Lost Ark. I specified the game id in the games-array, but the bot couldn't find any campaigns while there are some I checked. The error was that I added the game id to the games-array as integer and not as string. This should result in an error or at least a warning or should be allowed and not fail like it did for me.

**Comment by TychoTheTaco** [comment]
Good idea, just pushed a commit to address that.
