### ISSUE TITLE
[Game Request] Destiny 2

### ISSUE THREAD

**Issue by NoxRare** [TychoTheTaco/Twitch-Drops-Bot#60]
As the title says, I was wondering if support for Destiny 2 could be added!

**Comment by TychoTheTaco** [comment]
It already supports any game that has time based drops, you just need to know the game ID (`games.csv` is not a complete list).

The game ID for Destiny 2 is `497057`

**Comment by TychoTheTaco** [comment]
I just updated games.csv with the ID for Payday 2. I also added some steps in the readme that you can follow to find a game ID yourself in the future if it is missing from games.csv.

**Comment by SekiBetu** [comment]
> I just updated games.csv with the ID for Payday 2. I also added some steps in the readme that you can follow to find a game ID yourself in the future if it is missing from games.csv.

Thanks！
