### ISSUE TITLE
Broadcasters not working sometimes, view only listed streamers

### ISSUE THREAD

**Issue by yukaiin** [TychoTheTaco/Twitch-Drops-Bot#61]
So sometimes if i set my broadcasters the stream just wont load for them. Can't recreate it by now. I changed nothing and now it's working. Probably my wifi or something. Another thing is that it doest switch back to more preferred streamers. It only checks after the stream from the guy you don't wanna watch ended. Solution for this would be a timer that also auto reloads the broadcaster streams after the interval or just letting me activate broadcaster streams without activating "watch_streams_when_no_drop". First method would be probably nicer but if both get implemented that would be really nice. Thanks for keeping it updated. I really appreciate your work.

**Comment by TychoTheTaco** [comment]
First problem sounds like a connection issue.

Second problem is fixed in the latest commit, the bot will check every 5 minutes for a higher priority stream.
