### ISSUE TITLE
[Bug] Very often get the message "Error watching stream"

### ISSUE THREAD

**Issue by Pilotkosinus** [TychoTheTaco/Twitch-Drops-Bot#73]
I use the bot on my Raspberry Pi 4 with 2 GB RAM. The OS is Raspbian OS Lite 64bit. 

Every time I start the Docker container I get 2 to 20 times the message "Error watching stream". Sometimes it doesn't even manage to connect to the stream.

I read in an older issue that it is because the internet connection is too bad. I have it connected to a 1gb line (wifi only). I also read there that you can extend the time before it says error, so that it has more time to load the stream.

**Comment by NoxRare** [comment]
Try changing these settings:
load_timeout_secs
failed_stream_timeout

I have changed mine to 60 and 30.

**Comment by Pilotkosinus** [comment]
Thanks it seems like that solved my problem. Thank you for answering me so quickly.
