### ISSUE TITLE
fsevents module not supported on Windows

### ISSUE THREAD

**Issue by agret** [TychoTheTaco/Twitch-Drops-Bot#84]
![image](https://user-images.githubusercontent.com/568523/164647927-212df45c-b748-4528-8f2a-2dee3c7ee720.png)

![image](https://user-images.githubusercontent.com/568523/164647950-ae73924d-dc3b-419d-911c-9944c934af42.png)

**Comment by TychoTheTaco** [comment]
This is an old version of the code. Please `git pull` the latest commit.

**Comment by agret** [comment]
Thanks you are correct, was an old version. I deleted the local copy and checked out again. Followed new install instructions on the git page. Had to manually install 'prompt' via command 'npm install prompt' as it didn't install automatically with 'npm install'

Now I have run the npm run build & npm run start:



```
```
M:\Development\Twitch-Drops-Bot>npm run build

> twitch_drops_bot@1.0.1 build
> npm run clean && npm run compile


> twitch_drops_bot@1.0.1 clean
> rimraf dist


> twitch_drops_bot@1.0.1 compile
> tsc --pretty


M:\Development\Twitch-Drops-Bot>npm run start

> twitch_drops_bot@1.0.1 start
> node dist/index.js

[2022-04-26 21:18:37] [info] Loading config file: config.json
(node:23432) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[2022-04-26 21:18:38] [error] TypeError: numbersA.at is not a function
    at compareVersionString (file:///M:/Development/Twitch-Drops-Bot/dist/utils.js:45:40)
    at file:///M:/Development/Twitch-Drops-Bot/dist/index.js:183:17
    at Generator.next (<anonymous>)
    at fulfilled (file:///M:/Development/Twitch-Drops-Bot/dist/index.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

M:\Development\Twitch-Drops-Bot>
```
```

**Comment by TychoTheTaco** [comment]
I can't reproduce this. What is your nodejs version?

**Comment by agret** [comment]
Thanks, I had made sure my npm was up to date but didn't check nodejs.
I was running a nodejs version 14 build, updated to nodejs 16 and all good now.
