### ISSUE TITLE
[Bug] docker pull

### ISSUE THREAD

**Issue by BulldozerPete** [TychoTheTaco/Twitch-Drops-Bot#89]
**Describe the bug**
I run:
docker pull ghcr.io/tychothetaco/twitch-drops-bot:latest-release

I have received the error message: 
Error response from daemon: manifest unknown

**Screenshots**

**Logs**
Please post any relevant logs here. Ideally, attach the entire log file.

**Comment by TychoTheTaco** [comment]
The current release is still using the tag `latest`, starting with the next release, it will change to `latest-release`. I probably should have waited with updating the readme, sorry for the confusion. You can `docker pull ghcr.io/tychothetaco/twitch-drops-bot:latest` to get the current latest release.

**Comment by TychoTheTaco** [comment]
The new release is now using the `latest-release` tag.
