### ISSUE TITLE
[Feature Request] make twitch-bot-container run at startup

### ISSUE THREAD

**Issue by BulldozerPete** [TychoTheTaco/Twitch-Drops-Bot#98]
Hey, 

I am using your twitch-bot and would like to use a script to start the container if my raspberry needs to restart or after a power failure.
Is docker-compose the right tool for that?
But then no „there is an updated container available“ message would appear, right?

Maybe some users have found a way to automate this.

**Comment by TychoTheTaco** [comment]
I think you can do this with just an extra docker argument (https://docs.docker.com/config/containers/start-containers-automatically/)

Although what I do on my server is I just have a script that is run 5 minutes after reboot using crontab, and the script calls the docker run commands.

**Comment by BulldozerPete** [comment]
Can you share your script?

**Comment by TychoTheTaco** [comment]
I'm using `tmux` as well, but here it is
```
#!/bin/bash

function startTmuxSession {
	name=$1
	shift
	tmux new -d -s $name
	arr=("$@")
	for command in "${arr[@]}"
	do
		tmux send-keys -t "$name" "$command" ENTER
	done 
}

# Starting other things...

# Twitch Drops Bot
commands=("cd ~/code/Twitch-Drops-Bot" "docker run --rm -v ~/code/Twitch-Drops-Bot:/app/data -i -t --sig-proxy=false ghcr.io/tychothetaco/twitch-drops-bot")
startTmuxSession tdb "${commands[@]}"
```

If you just want to start the bot then this should be all you need. Just replace `~/code/Twitch-Drops-Bot` with the directory where your config is.
```
#!/bin/bash

docker run --rm -v ~/code/Twitch-Drops-Bot:/app/data -i -t --sig-proxy=false ghcr.io/tychothetaco/twitch-drops-bot
```
