### ISSUE TITLE
logon

### ISSUE THREAD

**Issue by idimo** [TychoTheTaco/Twitch-Drops-Bot#99]
I don't know if it's a bug or not but after restarting script, need to re-enter your twitch username and password and re-enter the 2fa code from the email, set up everything according to the instructions, tell me what am I doing wrong?

how to make that don't have to constantly enter your username and password at startup?

this was not the case with the old version, I logged into twitch once and after restarting the script, I farmed the drops logged in

**Comment by TychoTheTaco** [comment]
You need to have the username in the config. If that doesn't work, can you share the logs?

**Comment by idimo** [comment]
in what form should it be specified in the config.json? "username": login_you_accout, ?

**Comment by TychoTheTaco** [comment]
Yes, `"username": "my_twitch_username"`

**Comment by idimo** [comment]
great, it works, thank you for helping, love you man, but why is this not in the usage guide? 

never have guessed how to do it correctly

I also have a second account, how do I add it to this script?

"username": "my_twitch_username, my_twitch_username2", right?

**Comment by idimo** [comment]
and another question, but how to disable the "Hardware Media Key Handling" so that it does not appear as in the screenshot when the volume changes?

tried to change this setting when browser opening for entering my username and password here "chrome://flags/#hardware-media-key-handling", but after restarting the script, the settings were reset

wrote it in config.json is "--disable-hardware-media-key-handling", but I'm not sure that it works

![image](https://user-images.githubusercontent.com/75911190/167558076-d69cce18-9827-41fa-86ff-f74f5af62dff.png)

**Comment by TychoTheTaco** [comment]
I'll add some more details to the readme.

Right now, the bot only supports 1 account at a time. If you want to do more, you can start 2 bots, each with a different config.

I think you can disable that by adding this to the config:
```
"browser_args": [
    "--disable-features=HardwareMediaKeyHandling"
]
```

**Comment by whyphyrl** [comment]
Dont know if u need this but atm i use it like this 

A Batchfile like this:
(C:\AllGames is where the config is)
( the --name Bot1 is for Docker its names the Container so i now which one isnt up or something)

cd "C:\allgames"
docker run -v %cd%:/app/data -i -t --sig-proxy=false --rm --name Bot1 ghcr.io/tychothetaco/twitch-drops-bot --username ************ --password *********

**Comment by idimo** [comment]
> I think you can disable that by adding this to the config:
> 
> ```
> "browser_args": [
>     "--disable-features=HardwareMediaKeyHandling"
> ]
> ```

thank you man, I'll try this, you best

**Comment by idimo** [comment]
> Dont know if u need this but atm i use it like this
> 
> A Batchfile like this: (C:\AllGames is where the config is) ( the --name Bot1 is for Docker its names the Container so i know which one isnt up or something)
> 
> cd "C:\allgames" docker run -v %cd%:/app/data -i -t --sig-proxy=false --rm --name Bot1 ghcr.io/tychothetaco/twitch-drops-bot --username ************ --password *********

and you thank, but I use a script without docker, so maybe someone who uses it will be glad of your advice
